apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: sealos-cockroachdb
  namespace: sealos
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
        volumeMode: Filesystem
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 256Mi
  tlsEnabled: true
  cockroachDBVersion: v23.1.11
  nodes: 3